[package]
name = "embedded-svc"
version = "0.1.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "hal"]
description = "A set of traits for services higher level than embedded-hal and typically found in embedded microcontrollers."
repository = "https://github.com/ivmarkov/embedded-svc"
license = "MIT"

[dependencies]
anyhow = "1.0"
log = "0.4"
async-trait = "0.1"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
strum = "0.20"
strum_macros = "0.20"
getrandom = {git = "https://github.com/ivmarkov/getrandom.git", branch = "0.1", version = "0.1"}
http-auth-basic = "0.1"
bincode = "1.3"
url = "2.1"
