[package]
name = "embedded-svc"
version = "0.7.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "hal"]
description = "A set of traits for services higher level than embedded-hal and typically found in embedded microcontrollers with WiFi or BLE support."
repository = "https://github.com/ivmarkov/embedded-svc"
license = "MIT"
readme = "README.md"

[features]
default = ["std", "use_serde", "use_strum", "use_numenum"]

std = ["alloc", "anyhow/std", "serde/std", "serde_json/std", "url", "http-auth-basic"]
alloc = ["anyhow", "serde/alloc", "serde_json/alloc"]
use_serde = ["serde", "serde_json", "enumset/serde"]
use_strum = ["strum", "strum_macros"]
use_numenum = ["num_enum"]

[dependencies]
log = "0.4"
async-trait = "0.1"
no-std-net = "0.5"
enumset = "1"
anyhow = { version = "1", optional = true }
strum = { version = "0.21", optional = true }
strum_macros = { version = "0.21", optional = true }
num_enum = { version = "0.5", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
serde_json = { version = "1", optional = true }
url = { version = "2", optional = true }
http-auth-basic = { version = "0.1", optional = true }
