name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '50 4 * * *'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: Setup | Std
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default nightly
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Build | Clippy
        run: cargo clippy --no-deps --target riscv32imc-esp-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort -- -Dwarnings
      - name: Build | Compile / no_std, experimental
        run: cargo build --no-default-features --features experimental,alloc,use_serde,use_strum,use_numenum --target riscv32imc-esp-espidf -Zbuild-std=core,panic_abort -Zbuild-std-features=panic_immediate_abort
